apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleil
  template:
    metadata:
      labels:
        app: sleil
    spec:
      containers:
      - image: okteto.dev/sleil:latest
        name: sleil
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8e0b8667-0c86-4f2d-a158-87f75bc37a92"
        - name: Vless_Path
          value: "/vlejryu"
        - name: Vmess_UUID
          value: "8e0b8667-0c86-4f2d-a158-87f75bc37a92"
        - name: Vmess_Path
          value: "/vmrvhtd"
        - name: Share_Path
          value: "/v2link"
